#!/usr/bin/env zsh

# --- Sourcing ---
. $ZDOTDIR/config.zsh
. $ZDOTDIR/.zprofile
. $ZDOTDIR/aliases.zsh
# for now using powerlevel10k instead
# [ -f "~/.config/zsh/theming.zsh" ] && . "~/.config/zsh/theming.zsh"

# Install & source grml-zsh-config
if [[ ! -f $ZDOTDIR/.grmlrc ]]; then
  echo "Fetching grml"
  wget -O $ZDOTDIR/.grmlrc https://git.grml.org/f/grml-etc-core/etc/zsh/zshrc
fi
. $ZDOTDIR/.grmlrc

# XXX: todo
# if [ -f "/usr/share/nvm/init-nvm.sh" ]; then
#   # init-nvm.sh contents with bash_completion excluded and nvm dir changed
#   [ -z "$NVM_DIR" ] && export NVM_DIR="$HOME/.config/nvm"
#   source /usr/share/nvm/nvm.sh
#   source /usr/share/nvm/install-nvm-exec
# fi

# --- Antidote (https://getantidote.github.io/) ---
# run 'antidote update' to update plugins

# NOTE ANTIDOTE_DIR is forward-declared in modules/shell/zsh.nix
if [[ ! -d $ANTIDOTE_DIR ]]; then
  echo "Installing mattmc3/antidote"
  git clone https://github.com/mattmc3/antidote.git "$ANTIDOTE_DIR"
fi
. $ANTIDOTE_DIR/antidote.zsh
antidote load $ZDOTDIR/plugins

# stty stop undef # disable C-s to freeze terminal
# Nobody needs flow control anymore. Troublesome feature.
#stty -ixon
setopt noflowcontrol
# eval "$(zoxide init zsh)" # REVIEW: whether i need it or not..

## Bootstrap interactive sessions
if [[ $TERM != dumb ]]; then
  autoload -Uz compinit && compinit -u -d $ZSH_CACHE/zcompdump

  source $ZDOTDIR/keybinds.zsh
  # source $ZDOTDIR/completion.zsh # Redundant for now cuz using grml
  source $ZDOTDIR/aliases.zsh

  # Auto-generated by nixos
  _source $ZDOTDIR/extra.zshrc
  # If you have host-local configuration, put it here
  _source $ZDOTDIR/local.zshrc

  _cache fasd --init posix-alias zsh-{hook,{c,w}comp{,-install}}
  autopair-init
fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
